_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types: null
scenario_tokens:
  - 5056deefc1115299
  - de3c268de4395001 
  - a9636df727835fc8 
  - df0f6eaa728254ba 
  - 1990effcb0f55bd2 
  - 5fb5ddffbdc651c3 
  - 0afddce0959257f9 
  - 205908c8f73756d9 
  - 03ee30b099635920 
  - c9bc00d0f48b5bc1 
  - 878fafdc99cc592b 
  - e0cd66542e715685 
  - 329457a744415fd2 
  - e668948b1c0f5b82 
  - 52bd18c9f5db513a
  - 90e30f7bf082576a
  - a59a8c3490f154e2
  - f690276c57675cd5
  - 9febc58469ac56c2
  - b7e64de3350e5118
  - c881b474ecc256ac 
  - b52c963ae9175824 
  - 34ac5c7f439b561a 
  - 93a905027499542c 


log_names: null                     # Filter scenarios by log names
map_names: null                     # Filter scenarios by map names

num_scenarios_per_type: null        # Number of scenarios per type
limit_total_scenarios: null         # Limit total scenarios (float = fraction, int = num) - this filter can be applied on top of num_scenarios_per_type
timestamp_threshold_s: null         # Filter scenarios to ensure scenarios have more than `timestamp_threshold_s` seconds between their initial lidar timestamps
ego_displacement_minimum_m: null    # Whether to remove scenarios where the ego moves less than a certain amount
ego_start_speed_threshold: null     # Limit to scenarios where the ego reaches a certain speed from below
ego_stop_speed_threshold: null      # Limit to scenarios where the ego reaches a certain speed from above
speed_noise_tolerance: null         # Value at or below which a speed change between two timepoints should be ignored as noise.


expand_scenarios: false             # Whether to expand multi-sample scenarios to multiple single-sample scenarios
remove_invalid_goals: false         # Whether to remove scenarios where the mission goal is invalid
shuffle: false      